name: Checks

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Navigate into directory
        run: cd src/client

      - name: Install Dependencies
        run: npm install
        env:
          CI: true  # Setting CI environment variable to prevent progress bars

      - name: Run Tests
        run: npm test
        env:
          CI: true  # Setting CI environment variable to prevent progress bars

      # Adding a step to display the summary
      - name: Show Summary
        run: |
          echo "Test step completed: $GITHUB_STEP_SUMMARY"
