name: Checks

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: | 
          cd src/client
          npm install

      - name: Run Tests
        run: |
          cd src/client
          npm test

      - name: Process jest results with default
        if: always()
        uses: im-open/process-jest-test-results@v2.1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          results-file: 'src/client/__tests__/jest-results.json'

      - name: Show Summary
        run: |
          echo '### Tests completed! 🚀' >> $GITHUB_STEP_SUMMARY
