name: Checks

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: | 
          cd src/client
          npm install

      - name: Run Tests and Capture Output
        id: run_tests
        run: |
          cd src/client
          npm test
          cd __tests__
          echo "::set-output name=results::$(cat jest-results.json)"

      - name: Show Summary
        run: |
          echo "Test step completed: $GITHUB_STEP_SUMMARY"
          echo "Jest Test Results:"
          echo "$RESULTS" | jq -r '.testResults[] | "Test Suite: \(.name)\nPassed Tests: \(.numPassedTests)\nFailed Tests: \(.numFailedTests)\nTotal Tests: \(.numTotalTests)\n"'
        env:
          RESULTS: ${{ steps.run_tests.outputs.results }}
